# Generated by Django 3.2.9 on 2021-11-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='category',
            field=models.CharField(choices=[('Action & Adventure', 'Action & Adventure'), ('Comic Book or Graphic Novel', 'Comic Book or Graphic Novel'), ('Classics', 'Classics'), ('Detective & Mystery', 'Detective & Mystery'), ('Historical Fiction', 'Historical Fiction'), ('Fantasy', 'Fantasy'), ('Horror', 'Horror'), ('Literary Fiction', 'Literary Fiction')], max_length=225),
        ),
    ]
