# Generated by Django 3.2.9 on 2021-11-10 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_books_publiser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='category',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='books',
            name='publiser',
            field=models.CharField(max_length=225),
        ),
    ]
